### ISSUE TITLE
StackOverflow occurs when using parallel methods with TraceT

### ISSUE THREAD

**Issue by LiuVII** [ccadllc/cedi-dtrace#77]
Trying to replicate an issue we came up with this example
```scala
scala> (1 to 100000).toVector.parTraverse(_ => TraceIO.unit).toIO.unsafeRunSync
java.lang.StackOverflowError
  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:447)
  at java.lang.StringBuilder.append(StringBuilder.java:136)
  at java.lang.StringBuilder.append(StringBuilder.java:131)
  at com.ccadllc.cedi.dtrace.TraceSystem$Timer$RealTime.<init>(TraceSystem.scala:146)
  at com.ccadllc.cedi.dtrace.TraceSystem$Timer$RealTime.copy(TraceSystem.scala:145)
  at com.ccadllc.cedi.dtrace.TraceSystem$Timer$RealTime.translate(TraceSystem.scala:148)
  at com.ccadllc.cedi.dtrace.package$.translate(dtrace.scala:257)
  at com.ccadllc.cedi.dtrace.TraceTNonEmptyParallelInstance$NonEmptyParallelTraceT$$anon$10.$anonfun$apply$2(TraceT.scala:803)
  at com.ccadllc.cedi.dtrace.TraceTParallelInstance$ParallelTraceT$$anon$5.$anonfun$map$2(TraceT.scala:732)
  at com.ccadllc.cedi.dtrace.TraceTParallelInstance$ParallelTraceT$$anon$5.$anonfun$ap$1(TraceT.scala:736)
  at com.ccadllc.cedi.dtrace.TraceTParallelInstance$ParallelTraceT$$anon$5.$anonfun$map$2(TraceT.scala:732)
  at com.ccadllc.cedi.dtrace.TraceTParallelInstance$ParallelTraceT$$anon$5.$anonfun$ap$1(TraceT.scala:736)
  at com.ccadllc.cedi.dtrace.TraceTParallelInstance$ParallelTraceT$$anon$5.$anonfun$map$2(TraceT.scala:732)
  at com.ccadllc.cedi.dtrace.TraceTParallelInstance$ParallelTraceT$$anon$5.$anonfun$ap$1(TraceT.scala:736)
```
^ these last two lines keep repeataing

Looks strange considering that `toIO` just appends one span to the whole computation and never emits it (as we're using NoOp emitter)
Also, works fine with `traverse` on scales like tens of millions without any issues and the same works fine with just `IO` both for `traverse` or `parTraverse`

Not sure if there's implementation detail one should be aware of or there's a bug, but would appreciate any help 😅

**Comment by LiuVII** [comment]
Another thing to note, this doesn't happen for a low number, like <10k

**Comment by sbuzzard** [comment]
okay I have a "fix" - it's more like a hack, but no more a hack than the rest of the stack safety mechanism used in dtrace.  Adding first-class stack safety will be my next task but this should be useable once I get the fix merged in - PR soon.

**Comment by LiuVII** [comment]
Wooo! I'll take a hack over StackOverflow any day =)
lmk when it'll be merged and if there's gonna be some one-off or regular release

**Comment by sbuzzard** [comment]
i'll cut a 2.0.2 this weekend at the latest.

**Comment by sbuzzard** [comment]
published v2.0.2 with the fix.

**Comment by LiuVII** [comment]
niiiice!
does it take time to become available? don't see it in sonatype snapshots or releases:
https://repo1.maven.org/maven2/com/ccadllc/cedi/dtrace-core_2.12/

**Comment by sbuzzard** [comment]
It would help if I released it. :-)  I closed it in sonatype and was waiting for that to take effect and forgot to subsequently release it.

**Comment by sbuzzard** [comment]
okay, I released so should be available in the next few hours.
